[mf6_input]
component = "GWF"
subcomponent = "CHD"
blockname = [ "options", "dimensions", "period",]
multi_package = true
advanced = false
subpackage = []

[block]
[[block.options]]
name = "auxiliary"
longname = "keyword to specify aux variables"
type = "string"
block_variable = false
valid = []
shape = "(naux)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "auxiliary"
description = "REPLACE auxnames {'{#1}': 'Groundwater Flow'}"
deprecated = ""

[[block.options]]
name = "auxmultname"
longname = "name of auxiliary variable for multiplier"
type = "string"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "auxmultname"
description = "REPLACE auxmultname {'{#1}': 'CHD head value'}"
deprecated = ""

[[block.options]]
name = "boundnames"
longname = ""
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "boundnames"
description = "REPLACE boundnames {'{#1}': 'constant-head'}"
deprecated = ""

[[block.options]]
name = "print_input"
longname = "print input to listing file"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "iprpak"
description = "REPLACE print_input {'{#1}': 'constant-head'}"
deprecated = ""

[[block.options]]
name = "print_flows"
longname = "print CHD flows to listing file"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "iprflow"
description = "REPLACE print_flows {'{#1}': 'constant-head'}"
deprecated = ""

[[block.options]]
name = "save_flows"
longname = "save CHD flows to budget file"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "ipakcb"
description = "REPLACE save_flows {'{#1}': 'constant-head'}"
deprecated = ""

[[block.options]]
name = "ts_filerecord"
longname = ""
type = "record ts6 filein ts6_filename"
block_variable = false
valid = []
shape = ""
tagged = "true"
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "ts_filerecord"
description = ""
deprecated = ""

[[block.options]]
name = "ts6"
longname = "head keyword"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = "true"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = false
numeric_index = false
mf6internal = "ts6"
description = "keyword to specify that record corresponds to a time-series file."
deprecated = ""

[[block.options]]
name = "filein"
longname = "file keyword"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = "true"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = false
numeric_index = false
mf6internal = "filein"
description = "keyword to specify that an input filename is expected next."
deprecated = ""

[[block.options]]
name = "ts6_filename"
longname = "file name of time series information"
type = "string"
block_variable = false
valid = []
shape = ""
tagged = "false"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = "true"
numeric_index = false
mf6internal = "ts6_filename"
description = "REPLACE timeseriesfile {}"
deprecated = ""

[[block.options]]
name = "obs_filerecord"
longname = ""
type = "record obs6 filein obs6_filename"
block_variable = false
valid = []
shape = ""
tagged = "true"
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "obs_filerecord"
description = ""
deprecated = ""

[[block.options]]
name = "obs6"
longname = "obs keyword"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = "true"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = false
numeric_index = false
mf6internal = "obs6"
description = "keyword to specify that record corresponds to an observations file."
deprecated = ""

[[block.options]]
name = "obs6_filename"
longname = "obs6 input filename"
type = "string"
block_variable = false
valid = []
shape = ""
tagged = "false"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = "true"
numeric_index = false
mf6internal = "obs6_filename"
description = "REPLACE obs6_filename {'{#1}': 'constant-head'}"
deprecated = ""

[[block.options]]
name = "dev_no_newton"
longname = "turn off Newton for unconfined cells"
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "inewton"
description = "turn off Newton for unconfined cells"
deprecated = ""

[[block.dimensions]]
name = "maxbound"
longname = "maximum number of constant heads"
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = "false"
preserve_case = false
numeric_index = false
mf6internal = "maxbound"
description = "REPLACE maxbound {'{#1}': 'constant-head'}"
deprecated = ""

[[block.period]]
name = "stress_period_data"
longname = ""
type = "recarray cellid head aux boundname"
block_variable = false
valid = []
shape = "(maxbound)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
mf6internal = "spd"
description = ""
deprecated = ""

[[block.period]]
name = "cellid"
longname = "cell identifier"
type = "integer"
block_variable = false
valid = []
shape = "(ncelldim)"
tagged = "false"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
mf6internal = "cellid"
description = "REPLACE cellid {}"
deprecated = ""

[[block.period]]
name = "head"
longname = "head value assigned to constant head"
type = "double precision"
block_variable = false
valid = []
shape = ""
tagged = "false"
in_record = "true"
layered = false
time_series = "true"
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
mf6internal = "head"
description = "is the head at the boundary. If the Options block includes a TIMESERIESFILE entry (see the ``Time-Variable Input'' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
deprecated = ""

[[block.period]]
name = "aux"
longname = "auxiliary variables"
type = "double precision"
block_variable = false
valid = []
shape = "(naux)"
tagged = "false"
in_record = "true"
layered = false
time_series = "true"
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "auxvar"
description = "REPLACE aux {'{#1}': 'constant head'}"
deprecated = ""

[[block.period]]
name = "boundname"
longname = "constant head boundary name"
type = "string"
block_variable = false
valid = []
shape = ""
tagged = "false"
in_record = "true"
layered = false
time_series = false
reader = "urword"
optional = "true"
preserve_case = false
numeric_index = false
mf6internal = "boundname"
description = "REPLACE boundname {'{#1}': 'constant head boundary'}"
deprecated = ""

